# Generated by Django 6.0.4 on 2026-04-14 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=100, unique=True, verbose_name='Название (slug)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Бизнес-объект',
                'verbose_name_plural': 'Бизнес-объекты',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='AccessRoleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_perm', models.BooleanField(default=False, verbose_name='Чтение')),
                ('read_all_perm', models.BooleanField(default=False, verbose_name='Чтение всех')),
                ('create_perm', models.BooleanField(default=False, verbose_name='Создание')),
                ('update_perm', models.BooleanField(default=False, verbose_name='Редактирование')),
                ('update_all_perm', models.BooleanField(default=False, verbose_name='Редактирование всех')),
                ('delete_perm', models.BooleanField(default=False, verbose_name='Удаление')),
                ('delete_all_perm', models.BooleanField(default=False, verbose_name='Удаление всех')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access_control.businesselement', verbose_name='Бизнес-объект')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access_control.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Правило доступа',
                'verbose_name_plural': 'Правила доступа',
                'unique_together': {('role', 'element')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='access_control.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
